### ISSUE TITLE
Filter isn't striping out product microdata from GTM

### ISSUE THREAD

**Issue by JeffreyBurns** [SchemaApp/schema-filter#1]
We've implemented the filter through GTM and published to all pages. However, it doesn't seem to be removing the microdata.

**Comment by vberkel** [comment]
issue is that the onLoad event is past by the time this loads. Need to hook a GTM event, e.g. gtm.dom
See https://www.simoahava.com/analytics/trigger-guide-google-tag-manager/ for more information on gtm events.

**Comment by joelacummings** [comment]
It now removes it on the page, however, the SDTT is not seeing that. Not sure what would be causing that @vberkel any ideas? Also testing in browserling and content was removed:

**Comment by vberkel** [comment]
@JeffreyBurns, let's leave it in place as-is until we see the data in Search Console.

**Comment by joelacummings** [comment]
Based on my test of this page No Microdata is found.
